### ISSUE TITLE
Link to patch required for Mod is broken?

### ISSUE THREAD

**Issue by Tekwizard99** [CamelCaseName/HPFreecam#1]
So I went to install the mod, and it doesn't work. The MelonLoader patch link is also dead.

**Comment by CamelCaseName** [comment]
its up now

**Comment by CamelCaseName** [comment]
fixing it for the release version took longer than anticipated, but it is by now already compatible with the next release of house party, so all set for the future :)

**Comment by Tekwizard99** [comment]
Thanks man, I appreciate it!
